apt-get install python3
apt-get install python3-pip
apt-get install mono-devel
apt-get install nasm
pip3 install pycrypto
pip3 install cheroot
pip3 install flask
pip3 install donut-shellcode==0.9.2
pip3 install pypykatz
pip3 install tabulate
pip3 install rich
