import random

beacon_obf = ''


def obfvar(payload):
    global beacon_obf
    # print(payload)
    f = open("core/lib/obf.list", "r")
    links = f.read()
    list_full = links.strip().replace("\r", "").split("\n")  # replace("\0","").replace("\n",",").split(",")

    obf = random.choice(list_full)
    payload = payload.replace('{a}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{agent}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{arch}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{b}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{badoutput}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    beacon_obf = obf
    payload = payload.replace('{bea}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{cm}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{data}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{date}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{domain}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{e}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{enc}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{f}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{file}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{finaldata}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{hostname}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{IP}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{IV}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{kdate}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{key}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{max}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{min}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{module}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{modulename}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{os}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{output}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{p}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{pid}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{postParams}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{progressPreference}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{rand}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{random}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{result}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{redata}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{seed}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{t}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{un}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{wc3}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{whoami}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{req}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)

    payload = payload.replace('{AGENTVAR}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    payload = payload.replace('{DATAVAR}', obf)
    list_full.remove(obf)
    obf = random.choice(list_full)
    return payload
